# Generated by Django 3.2.8 on 2021-11-18 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='Notes',
            new_name='notes',
        ),
    ]
